# see: https://www.appveyor.com/docs/appveyor-yml/
version: AppVeyor-{build}
skip_tags: true
skip_branch_with_pr: true

build_script:
  - main.bat

deploy:
  release: builder-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release of pentest tools tag created by AppVeyor build $(appveyor_build_version). Pass: $(_7Z_PASSWORD_)'
  provider: GitHub
  auth_token:
    secure: Mwy24X0ht3QBpQBpstLoG+1fKJzQL3wGgzEqMf7ThB88jrxfMLUcdZA14gDlgz+61fofJljpgrk9nTCQphpOurnylOOmTs2P1AP/vx/94WcrwAsuZDFlwwZLEcNyuYsJ # your encrypted token from GitHub
  # see https://www.appveyor.com/docs/packaging-artifacts/#packaging-multiple-files-in-different-locations-into-a-single-archive
  #artifact: '*.7z'
  draft: false
  prerelease: false
  force_update: true
