# see: https://www.appveyor.com/docs/appveyor-yml/
version: AppVeyor-{build}
skip_tags: true
skip_branch_with_pr: true

build_script:
  - main.bat

deploy:
  release: builder-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release of pentest tools tag created by AppVeyor build $(appveyor_build_version). Pass: $(_7Z_PASSWORD_)'
  provider: GitHub
  auth_token:
    secure: Mwy24X0ht3QBpQBpstLoG1jAXqCcF2Sfvtfvb2/tzH3td3GHFf5wRIic/ggfeOMFqGAo1QMB8ly18KB6jh0wRZVfHD/rtD+JsVBjt+YX++sLfbbFc7joMuwZsiUm0h/J # your encrypted token from GitHub
  # see https://www.appveyor.com/docs/packaging-artifacts/#packaging-multiple-files-in-different-locations-into-a-single-archive
  #artifact: '*.7z'
  draft: false
  prerelease: false
  force_update: true
