name:  Build and release

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - main
      - test-github-actions
jobs:
  build:
    permissions:
      contents: write # to upload release asset (softprops/action-gh-release)
    runs-on: windows-2019
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Installer pyinstaller
        run: pip install pyinstaller
      - name: "Update windows SDK"
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19041
      - name: Run script
        run: .\main.bat
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "./**/*.7z"
            "./**/*.log"
          tag_name: "${{ github.event.head_commit.message }}"
