name:  Build and release

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - main
      - test-github-actions
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: pyinstaller
      - name: Run script
        run: .\main.bat
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ".\\bin\\*.exe"
